### ISSUE TITLE
Sort Meals By Time

### ISSUE THREAD

**Issue by say25** [cuappdev/eatery#87]
![simulator screen shot dec 2 2015 7 55 18 pm](https://cloud.githubusercontent.com/assets/7467062/11548849/a56f1fe0-992e-11e5-826f-651e9ba7bf3f.png)

**Comment by say25** [comment]
@lucasderraugh and @dennisfedorko is this invalid now?

**Comment by lucasderraugh** [comment]
I don't think this is an issue anymore.
