### ISSUE TITLE
Enhance Search Bar

### ISSUE THREAD

**Issue by say25** [cuappdev/eatery#94]
Add "Search" text to bar
Fix odd issues

**Comment by lucasderraugh** [comment]
![img_0191](https://cloud.githubusercontent.com/assets/714282/12967398/3228f6fe-d034-11e5-9e8f-e03cb81c5647.jpg)
Change the search bar to something like this. Let's leave the search in the scrollview instead of the nav bar.

**Comment by say25** [comment]
Closed with #106
